Repository tickita-project/tickita-front, pull requests merged in 2024-06, with the labels that each got.

#19 feat: MetaData 컴포넌트 추가
  components/MetaData/index.tsx
  components/temp.tsx
  hooks/temp.tsx
  hooks/useCurrentPath.ts
  pages/index.page.tsx
  pages/test/index.module.scss
  pages/test/index.page.tsx
  public/Icons/logo.svg
  public/icons/.gitkeep
  public/images/.gitkeep
Labels: ⚙️ feat

#20 [feat] 로그인 페이지 구현
  apis/axios.ts
  pages/sign-in/index.module.scss
  pages/sign-in/index.page.tsx
  pages/sign-in/kakao/index.page.tsx
  public/icons/.gitkeep
  public/icons/google-icon.svg
  public/icons/kakao-icon.svg
  public/icons/tickita-fullname-logo.svg
  public/icons/tickita-logo.svg
  styles/_fonts.scss
  styles/reset.scss
Labels: ⚙️ feat

#12 [feat] 그룹 리스트 컴포넌트 추가
  .github/pull_request_template.md
  .github/workflows/preview.yml
  components/ColorCheckBox/ColorCheckBox.module.scss
  components/ColorCheckBox/index.tsx
  components/Header/Header.module.scss
  components/Header/index.tsx
  components/MetaData/index.tsx
  components/Modal/CreateGroup/CreateGroup.module.scss
  components/Modal/CreateGroup/index.tsx
  components/Modal/Portal/Portal.module.scss
  components/Modal/Portal/index.tsx
  constants/modalType.ts
  constants/pagePath.ts
  constants/temp.tsx
  pages/_app.page.tsx
  pages/dashboard/components/GroupList/GroupList.module.scss
  pages/dashboard/components/GroupList/index.tsx
  pages/dashboard/components/NotificationCenter/NotificationCenter.scss
  pages/dashboard/components/NotificationCenter/index.tsx
  pages/dashboard/components/ScheduleCoordination/UpcomingSchedules.module.scss
  pages/dashboard/components/ScheduleCoordination/index.tsx
  pages/dashboard/components/UpcomingSchedules/UpcomingSchedules.module.scss
  pages/dashboard/components/UpcomingSchedules/index.tsx
  pages/dashboard/index.page.tsx
  pages/index.page.tsx
  public/icons/default-profile.svg
  public/icons/plus-icon.svg
  store/useModalStore.ts
  store/useUserInfoStore.ts
  styles/_globals.scss
  styles/_mixin.scss
  types/temp.ts
  types/type.ts
  utils/getIsEnvironment.ts
  utils/temp.ts
Labels: ⚙️ feat

#13 [feat] DatePicker 컴포넌트 구현
  components/DatePicker/DatePicker.tsx
  components/DatePicker/datePicker.module.scss
  constants/calendarConstants.ts
  package-lock.json
  package.json
  pages/calendar/index.page.tsx
  public/icons/arrow-left-icon.svg
  public/icons/arrow-right-icon.svg
  public/icons/google-icon.svg
  public/icons/kakao-icon.svg
  public/icons/tickita-fullname-logo.svg
  public/icons/tickita-logo.svg
  public/icons/vertical-divider-icon.svg
  styles/_fonts.scss
Labels: ⚙️ feat

#22 [fix] 카카오 소셜 로그인 redirectURI 수정
  constants/pagePath.ts
  pages/profile-setup/index.page.tsx
  pages/sign-in/index.page.tsx
  pages/sign-in/kakao/index.page.tsx
  public/icons/google-icon.svg
  public/icons/kakao-icon.svg
  public/icons/tickita-fullname-logo.svg
  public/icons/tickita-logo.svg
Labels: 🛠️ fix

#23 [feat] 대시보드 작업
  components/DatePicker/DatePicker.tsx
  components/DatePicker/datePicker.module.scss
  components/Header/Header.module.scss
  components/Header/index.tsx
  components/Layout/Layout.module.scss
  components/Layout/index.tsx
  components/MetaData/index.tsx
  components/Notification/BaseNotification/BaseNotification.module.scss
  components/Notification/BaseNotification/index.tsx
  components/Notification/CoordinationNotification/index.tsx
  components/Notification/EmptyNotification/EmptyNotification.module.scss
  components/Notification/EmptyNotification/index.tsx
  components/Notification/SchduleInfoNotification/index.tsx
  constants/pagePath.ts
  pages/_app.page.tsx
  pages/calendar/index.page.tsx
  pages/dashboard/Dashboard.module.scss
  pages/dashboard/components/GroupList/GroupList.module.scss
  pages/dashboard/components/GroupList/index.tsx
  pages/dashboard/components/NotificationCenter/NotificationCenter.module.scss
  pages/dashboard/components/NotificationCenter/NotificationCenter.scss
  pages/dashboard/components/NotificationCenter/index.tsx
  pages/dashboard/components/ScheduleCoordination/UpcomingSchedules.module.scss
  pages/dashboard/components/ScheduleCoordination/index.tsx
  pages/dashboard/components/UpcomingScheduleList/UpcomingSchedule/UpcomingSchedule.module.scss
  pages/dashboard/components/UpcomingScheduleList/UpcomingSchedule/index.tsx
  pages/dashboard/components/UpcomingScheduleList/UpcomingScheduleList.module.scss
  pages/dashboard/components/UpcomingScheduleList/index.tsx
  pages/dashboard/components/UpcomingSchedules/UpcomingSchedules.module.scss
  pages/dashboard/components/UpcomingSchedules/index.tsx
  pages/dashboard/index.page.tsx
  public/favicon.ico
  public/icons/dashboard-calendar.svg
  public/icons/ghost.svg
  public/icons/group-arrow-right.svg
  public/icons/notification-close.svg
  public/icons/notification.svg
  public/images/.gitkeep
  public/images/kakao-og.webp
  public/images/twitter-og.webp
  styles/_mixin.scss
Labels: ⚙️ feat

#27 [feat] 이미지 프로필 컴포넌트 추가
  components/Header/Header.module.scss
  components/Header/index.tsx
  components/ProfileImage/ProfileImage.module.scss
  components/ProfileImage/index.tsx
  next.config.mjs
Labels: ⚙️ feat

#30 [feat] 캘린더페이지 사이드바 및 기본 레이아웃 설정
  components/ColorCheckBox/ColorCheckBox.module.scss
  components/ColorCheckBox/index.tsx
  components/DatePicker/DatePicker.tsx
  components/DatePicker/datePicker.module.scss
  hooks/useOutsideClick.ts
  pages/calendar/Calendar.module.scss
  pages/calendar/components/Calendar/DailyCalendar/DailyCalendar.module.scss
  pages/calendar/components/Calendar/DailyCalendar/index.tsx
  pages/calendar/components/Calendar/MonthlyCalendar/MonthlyCalendar.module.scss
  pages/calendar/components/Calendar/MonthlyCalendar/index.tsx
  pages/calendar/components/Calendar/WeeklyCalendar/WeeklyCalendar.module.scss
  pages/calendar/components/Calendar/WeeklyCalendar/index.tsx
  pages/calendar/components/CalendarGroupList/CalendarGroupList.module.scss
  pages/calendar/components/CalendarGroupList/index.tsx
  pages/calendar/components/CalendarSideBar/CalendarSideBar.module.scss
  pages/calendar/components/CalendarSideBar/index.tsx
  pages/calendar/components/CalendarTypeRadioButton/CalendarTypeRadioButton.module.scss
  pages/calendar/components/CalendarTypeRadioButton/index.tsx
  pages/calendar/components/TimeTable/TimeTable.module.scss
  pages/calendar/components/TimeTable/index.tsx
  pages/calendar/index.page.tsx
  public/icons/schedule-icon.svg
  styles/_fonts.scss
  utils/calculateCalendarDates.ts
Labels: ⚙️ feat

#31 [feat] 추가 정보 입력 페이지 구현
  apis/apis.ts
  components/Input/Input.module.scss
  components/Input/index.tsx
  constants/formSchema.ts
  constants/pagePath.ts
  package-lock.json
  package.json
  pages/profile-setup/index.page.tsx
  pages/sign-in/kakao/index.page.tsx
  pages/sign-in/profile-setup/components/ProfileSetupForm/ProfileSetupForm.module.scss
  pages/sign-in/profile-setup/components/ProfileSetupForm/ProfileSetupForm.tsx
  pages/sign-in/profile-setup/index.module.scss
  pages/sign-in/profile-setup/index.page.tsx
  public/icons/profile-add-icon.svg
  types/type.ts
Labels: ⚙️ feat

#34 feat: 캘린더 헤더 컴포넌트 및 스크롤 훅 구현
  components/DatePicker/DatePicker.tsx
  components/DatePicker/MonthNavButton/MonthNavButton.module.scss
  components/DatePicker/MonthNavButton/index.tsx
  components/DatePicker/datePicker.module.scss
  hooks/useOutsideClick.ts
  hooks/useScroll.ts
  pages/calendar/Calendar.module.scss
  pages/calendar/components/Calendar/CalendarHeader/CalendarHeader.module.scss
  pages/calendar/components/Calendar/CalendarHeader/index.tsx
  pages/calendar/components/Calendar/DailyCalendar/index.tsx
  pages/calendar/components/Calendar/MonthlyCalendar/index.tsx
  pages/calendar/components/Calendar/WeeklyCalendar/index.tsx
  pages/calendar/components/CalendarGroupList/CalendarGroupList.module.scss
  pages/calendar/components/CalendarSideBar/index.tsx
  pages/calendar/components/CalendarTypeRadioButton/CalendarTypeRadioButton.module.scss
  pages/calendar/components/CalendarTypeSegmentedButton/CalendarTypeSegmentedButton.module.scss
  pages/calendar/components/CalendarTypeSegmentedButton/index.tsx
  pages/calendar/index.page.tsx
  pages/dashboard/index.page.tsx
  store/useDateStore.ts
  styles/_fonts.scss
Labels: ⚙️ feat, 🛠️ fix

#37 [feat] 디바운스 훅 작성
  components/DatePicker/DatePicker.tsx
  hooks/useDebounce.ts
Labels: ⚙️ feat

#38 [feat] 월간캘린더 디자인 구현
  components/DatePicker/DatePicker.tsx
  pages/calendar/components/Calendar/CalendarHeader/CalendarHeader.module.scss
  pages/calendar/components/Calendar/MonthlyCalendar/MonthlyCalendar.module.scss
  pages/calendar/components/Calendar/MonthlyCalendar/index.tsx
  pages/calendar/components/CalendarSideBar/CalendarSideBar.module.scss
  pages/calendar/components/CalendarTypeSegmentedButton/CalendarTypeSegmentedButton.module.scss
Labels: ⚙️ feat

#40 [feat] 로그인 시 쿠키에 토큰 저장
  apis/axios.ts
  pages/api/cookies.page.ts
  pages/sign-in/index.page.tsx
  pages/sign-in/kakao/index.page.tsx
  pages/sign-in/profile-setup/components/ProfileSetupForm/ProfileSetupForm.tsx
  types/type.ts
Labels: ⚙️ feat

#43 [feat] 헤더 유저 정보 가져오기
  apis/apis.ts
  components/ErrorFallBack/ErrorFallBack.module.scss
  components/ErrorFallBack/index.tsx
  components/Header/Header.module.scss
  components/Header/index.tsx
  components/ProfileImage/ProfileImage.module.scss
  components/ProfileImage/index.tsx
  constants/pagePath.ts
  constants/queryKey.ts
  hooks/useGetGroupList.ts
  hooks/useGetUserInfo.ts
  package-lock.json
  package.json
  pages/_app.page.tsx
  pages/calendar/index.page.tsx
  pages/dashboard/components/GroupList/index.tsx
  pages/dashboard/index.page.tsx
  public/images/error.webp
  styles/_colors.scss
  types/type.ts
  utils/getErrorMessage.ts
  utils/getIsEnvironment.ts
Labels: ⚙️ feat

#42 [feat] 추가정보 입력 시 이미지 추가 / access token 재발급
  apis/apis.ts
  apis/axios.ts
  middleware.page.ts
  middleware.ts
  pages/api/logout.page.ts
  pages/api/setCookies.page.ts
  pages/sign-in/kakao/index.page.tsx
  pages/sign-in/profile-setup/components/ProfileSetupForm/ProfileSetupForm.module.scss
  pages/sign-in/profile-setup/components/ProfileSetupForm/ProfileSetupForm.tsx
  pages/sign-in/profile-setup/index.module.scss
  pages/sign-in/profile-setup/index.page.tsx
  public/icons/camera-icon.svg
  public/icons/default-profile-image.svg
  public/icons/profile-add-icon.svg
  utils/getCookieValue.ts
Labels: ⚙️ feat

#46 [feat] 일간, 주간 캘린더 디자인 및 query 설정
  .eslintrc.json
  components/DatePicker/DatePicker.tsx
  components/DatePicker/MonthNavButton/index.tsx
  constants/calendarConstants.ts
  pages/calendar/components/Calendar/CalendarHeader/index.tsx
  pages/calendar/components/Calendar/DailyCalendar/DailyCalendar.module.scss
  pages/calendar/components/Calendar/DailyCalendar/index.tsx
  pages/calendar/components/Calendar/MonthlyCalendar/index.tsx
  pages/calendar/components/Calendar/WeeklyCalendar/WeeklyCalendar.module.scss
  pages/calendar/components/Calendar/WeeklyCalendar/index.tsx
  pages/calendar/components/CalendarTypeSegmentedButton/index.tsx
  pages/calendar/components/TimeTable/TimeTable.module.scss
  pages/calendar/components/TimeTable/index.tsx
  pages/calendar/index.page.tsx
  styles/_fonts.scss
  types/type.ts
  utils/calculateCalendarDates.ts
Labels: ⚙️ feat

#48 [fix] 에러 확인을 위한 코드 수정
  pages/sign-in/kakao/index.page.tsx
Labels: 🛠️ fix

#49 [fix] 코드 복구
  pages/sign-in/kakao/index.page.tsx
Labels: 🛠️ fix

#51 [feat] 로그인 로딩 페이지 및 `nextInstance` base URL 동적 변경
  apis/axios.ts
  package-lock.json
  package.json
  pages/sign-in/SignIn.module.scss
  pages/sign-in/index.page.tsx
  pages/sign-in/kakao/Kakao.module.scss
  pages/sign-in/kakao/index.page.tsx
  pages/sign-in/profile-setup/ProfileSetup.module.scss
  pages/sign-in/profile-setup/index.page.tsx
  public/images/login-loading.json
Labels: ⚙️ feat

#50 [feat] 그룹 상세 페이지
  apis/apis.ts
  components/ErrorFallBack/index.tsx
  components/GroupColorPicker/GroupColorPicker.module.scss
  components/Header/Header.module.scss
  components/Header/index.tsx
  components/Layout/Layout.module.scss
  components/Modal/CreateGroup/CreateGroup.module.scss
  components/ProfileImage/index.tsx
  components/TitleBox/TitleBox.module.scss
  components/TitleBox/index.tsx
  hooks/useGetGroupInfo.ts
  hooks/useGetUserInfo.ts
  hooks/useInviteGroupMember.ts
  hooks/useOutsideClick.ts
  pages/calendar/components/CalendarGroupList/index.tsx
  pages/calendar/components/CalendarSideBar/index.tsx
  pages/dashboard/components/GroupList/GroupList.module.scss
  pages/dashboard/components/GroupList/index.tsx
  pages/group/[id]/Group.module.scss
  pages/group/[id]/components/GroupForm/GroupForm.module.scss
  pages/group/[id]/components/GroupForm/index.tsx
  pages/group/[id]/components/InviteForm/InviteForm.module.scss
  pages/group/[id]/components/InviteForm/index.tsx
  pages/group/[id]/components/MemberList/MemberInfo/MemberInfo.module.scss
  pages/group/[id]/components/MemberList/MemberInfo/index.tsx
  pages/group/[id]/components/MemberList/MemberList.module.scss
  pages/group/[id]/components/MemberList/index.tsx
  pages/group/[id]/index.page.tsx
  pages/sign-in/kakao/index.page.tsx
  public/icons/hamburger-icon.svg
  public/icons/information-icon.svg
  public/icons/invite-empty.svg
  public/images/preview.webp
  types/type.ts
Labels: ⚙️ feat

#55 [feat]캘린더 드래그 기능 구현 및 일정생성 모달과 연결
  components/ColorCheckBox/ColorCheckBox.module.scss
  components/Modal/Portal/index.tsx
  components/Modal/Schedule/ScheduleCreate/index.tsx
  components/Modal/Schedule/ScheduleDetail/ScheduleModal.module.scss
  components/Modal/Schedule/ScheduleDetail/index.tsx
  components/Modal/Schedule/ScheduleEdit/index.tsx
  constants/modalType.ts
  hooks/useDragSelect.ts
  hooks/useOutsideClick.ts
  pages/calendar/components/Calendar/DailyCalendar/DailyCalendar.module.scss
  pages/calendar/components/Calendar/DailyCalendar/index.tsx
  pages/calendar/components/Calendar/MonthlyCalendar/MonthlyCalendar.module.scss
  pages/calendar/components/Calendar/MonthlyCalendar/index.tsx
  pages/calendar/components/Calendar/WeeklyCalendar/WeeklyCalendar.module.scss
  pages/calendar/components/Calendar/WeeklyCalendar/index.tsx
  pages/calendar/components/CalendarGroupList/CalendarGroupList.module.scss
  pages/calendar/index.page.tsx
  public/icons/location-icon.svg
  store/useDateStore.ts
  styles/_fonts.scss
  styles/_mixin.scss
  types/type.ts
Labels: ⚙️ feat

#68 [feat] 그룹 초대 수락 api 연결
  apis/apis.ts
  components/GroupColorPicker/GroupColorPicker.module.scss
  components/GroupColorPicker/index.tsx
  components/Input/Input.module.scss
  components/Modal/CreateGroup/index.tsx
  components/Modal/ExitGroup/index.tsx
  components/Notification/BaseNotification/index.tsx
  components/Notification/CoordinationNotification/index.tsx
  components/Notification/ScheduleInfoNotification/index.tsx
  constants/queryKey.ts
  hooks/useAcceptInvite.ts
  hooks/useGetAllNotification.ts
  pages/dashboard/components/NotificationCenter/index.tsx
  pages/dashboard/index.page.tsx
  pages/group/[id]/components/ActionButton/ActionButton.module.scss
  pages/group/[id]/components/GroupForm/index.tsx
  pages/group/[id]/components/MemberList/MemberInfo/index.tsx
  pages/group/[id]/index.page.tsx
  types/type.ts
  utils/formatKoreanDateTime.ts
Labels: ⚙️ feat

#72 [feat] 로그아웃 로직 추가
  components/Header/index.tsx
  pages/api/logout.page.ts
Labels: ⚙️ feat

#74 feat: 404 페이지 추가
  pages/404.page.tsx
  pages/_app.page.tsx
  styles/404.module.scss
  styles/reset.css
Labels: ⚙️ feat

#76 [fix] 빌드 시간 단축
  appspec.yml
  deploy.sh
Labels: 🛠️ fix

#66 [feat] 알림 팝업 구현
  components/Header/Header.module.scss
  components/Header/index.tsx
  components/Notification/BaseNotification/BaseNotification.module.scss
  components/Notification/BaseNotification/index.tsx
  components/NotificationPopup/NotificationPopup.module.scss
  components/NotificationPopup/index.tsx
  hooks/useGetProfileImage.ts
  pages/my-page/components/ProfileEditForm/index.tsx
  pages/my-page/index.page.tsx
  pages/sign-in/profile-setup/components/ProfileSetupForm/ProfileSetupForm.tsx
  utils/formatKoreanDateTime.ts
Labels: ⚙️ feat

#80 [fix] api response 데이터명 변경에 따른 오류 수정
  components/NotificationPopup/index.tsx
  pages/dashboard/components/NotificationCenter/index.tsx
  types/type.ts
Labels: 🛠️ fix

#83 [fix] 로그인 에러 확인
  pages/sign-in/kakao/index.page.tsx
Labels: 🛠️ fix

#88 [fix] pm2 명령어 수정
  deploy.sh
Labels: 🛠️ fix

#90 [fix] 배포 테스트
  pages/index.page.tsx
Labels: 🛠️ fix

#79 [feat]일정생성모달구현
  apis/apis.ts
  components/Modal/Portal/index.tsx
  components/Modal/Schedule/ScheduleCreate/ScheduleCreateModal.module.scss
  components/Modal/Schedule/ScheduleCreate/index.tsx
  components/Modal/Schedule/ScheduleDetail/ScheduleDetailModal.module.scss
  components/Modal/Schedule/ScheduleDetail/ScheduleModal.module.scss
  components/Modal/Schedule/ScheduleDetail/index.tsx
  constants/queryKey.ts
  hooks/useCreateSchedule.ts
  types/type.ts
Labels: ⚙️ feat

#82 [feat] 알림 확인, 삭제 api, 초대 취소 api 연결
  apis/apis.ts
  components/GroupColorPicker/index.tsx
  components/Modal/CancelInvite/index.tsx
  components/Notification/BaseNotification/BaseNotification.module.scss
  components/Notification/BaseNotification/index.tsx
  components/Notification/CoordinationNotification/index.tsx
  components/Notification/ScheduleInfoNotification/index.tsx
  hooks/useCheckNotification.ts
  hooks/useDeleteNotification.ts
  pages/dashboard/components/NotificationCenter/index.tsx
  pages/group/[id]/components/GroupForm/index.tsx
  types/type.ts
Labels: ⚙️ feat

#93 [feat] 랜딩 페이지 구현
  pages/Home.module.scss
  pages/index.page.tsx
  public/icons/landing-arrow.svg
  public/icons/landing-calendar.svg
  public/icons/landing-point-icon.svg
  public/images/calendar.json
  public/images/coordination-step1.webp
  public/images/coordination-step2.svg
  public/images/coordination-step3.svg
  public/images/coordination-step4.svg
  public/images/coordination-step5.svg
  public/images/green-postit.svg
  public/images/group-create.json
  public/images/member-manage.json
  public/images/orange-postit.svg
  public/images/pink-postit.svg
  public/images/postit-line.svg
Labels: ⚙️ feat

#95 [fix] 배포 사이트에서 랜딩 페이지 안보이는 오류 수정
  package-lock.json
  package.json
Labels: 🛠️ fix

#97 [refactor] 랜딩 페이지 Pull Page Scroll 추가
  appspec.yml
  deploy.sh
  pages/Home.module.scss
  pages/index.page.tsx
  styles/reset.css
Labels: 🔨 refactor

#98 [fix]: 배포 명령어 수정, 랜딩 페이지 스로톨링 추가
  deploy.sh
  package-lock.json
  package.json
  pages/index.page.tsx
Labels: 🛠️ fix

#99 [fix] 빌드 명령어 수정
  appspec.yml
  deploy.sh
  package.json
Labels: 🛠️ fix

#100 [refactor] 미들웨어 및 로그인 로직 수정
  middleware.page.ts
  pages/sign-in/index.page.tsx
  pages/sign-in/profile-setup/index.page.tsx
Labels: 🔨 refactor

#101 [fix] middleware를 통해 `/dashboard`로 이동 시 발생하는 오류 수정
  middleware.page.ts
Labels: 🛠️ fix

#102 [refactor] 토큰 에러 확인용 코드 삽입
  pages/sign-in/kakao/index.page.tsx
Labels: 🔨 refactor

#104 [fix] refresh token 있을 때도 로그인 가능하도록 수정
  middleware.page.ts
  pages/sign-in/kakao/index.page.tsx
Labels: 🛠️ fix

#105 [fix] access token `max-age` 5분으로 설정
  apis/axios.ts
  pages/api/setCookies.page.ts
  pages/sign-in/kakao/index.page.tsx
Labels: 🛠️ fix

#106 [fix] access token `max-age` 수정
  pages/api/setCookies.page.ts
  pages/sign-in/kakao/index.page.tsx
Labels: 🛠️ fix

#107 [feat] refresh token 가지고 있을 시, `/sign-in` 페이지 접근 불가
  middleware.page.ts
Labels: ⚙️ feat

#109 [feat] 토스트 추가
  components/Loader/Loader.module.css
  components/Loader/index.tsx
  components/Modal/CancelInvite/index.tsx
  components/Modal/ChangeLeader/index.tsx
  components/Modal/CreateGroup/index.tsx
  components/Modal/DeleteGroup/index.tsx
  components/Modal/ExitGroup/index.tsx
  components/Modal/ExportMember/index.tsx
  components/Notification/BaseNotification/index.tsx
  components/Toast/Toast.module.scss
  components/Toast/ToastMessage/ToastMessage.module.scss
  components/Toast/ToastMessage/index.tsx
  components/Toast/index.tsx
  hooks/useToast.tsx
  pages/_app.page.tsx
  pages/group/[id]/components/GroupForm/index.tsx
  pages/group/[id]/components/InviteForm/index.tsx
  public/icons/close.svg
  public/icons/error.svg
  public/icons/info.svg
  public/icons/success.svg
  public/icons/warning.svg
  services/toastService.ts
  types/type.ts
Labels: ⚙️ feat

#116 [feat]일정 데이터 캐싱, 일간캘린더 연동, 일간캘린더 스케줄 바 컴포넌트
  apis/apis.ts
  components/ColorCheckBox/index.tsx
  components/Modal/Portal/Portal.module.scss
  components/Modal/Schedule/ScheduleCreate/index.tsx
  hooks/useGetCrewSchedule.ts
  pages/calendar/components/Calendar/DailyCalendar/DailyCalendar.module.scss
  pages/calendar/components/Calendar/DailyCalendar/index.tsx
  pages/calendar/components/Calendar/MonthlyCalendar/index.tsx
  pages/calendar/components/Calendar/WeeklyCalendar/index.tsx
  pages/calendar/components/CalendarGroupList/index.tsx
  pages/calendar/components/CalendarSideBar/index.tsx
  pages/calendar/components/ScheduleBar/DailyScheduleBar/DailyScheduleBar.module.scss
  pages/calendar/components/ScheduleBar/DailyScheduleBar/index.tsx
  pages/calendar/index.page.tsx
  types/type.ts
Labels: ⚙️ feat

#118 [feat] 구글 로그인 기능 추가
  pages/sign-in/google/Google.module.scss
  pages/sign-in/google/index.page.tsx
  pages/sign-in/index.page.tsx
Labels: ⚙️ feat

#119 [fix] access token 만료 시간 변경
  pages/api/setCookies.page.ts
  pages/sign-in/google/index.page.tsx
  pages/sign-in/kakao/index.page.tsx
Labels: 🛠️ fix

#120 [feat] 회원 탈퇴 기능 추가
  apis/apis.ts
  pages/my-page/components/ProfileEditForm/ProfileEditForm.module.scss
  pages/my-page/components/ProfileEditForm/index.tsx
Labels: ⚙️ feat

#121 [fix] 배포 명령어 수정
  deploy.sh
Labels: 🛠️ fix

#126 [feat]일정상세 모달구현, 일정삭제 구현
  apis/apis.ts
  components/Modal/Schedule/ScheduleDetail/ScheduleDetailModal.module.scss
  components/Modal/Schedule/ScheduleDetail/index.tsx
  pages/calendar/components/Calendar/DailyCalendar/index.tsx
  pages/calendar/components/Calendar/MonthlyCalendar/index.tsx
  pages/calendar/components/ScheduleBar/DailyScheduleBar/index.tsx
  pages/calendar/components/ScheduleBar/WeeklyScheduleBar/index.tsx
  pages/calendar/index.page.tsx
  pages/dashboard/components/UpcomingScheduleList/UpcomingSchedule/index.tsx
  pages/dashboard/components/UpcomingScheduleList/index.tsx
  public/icons/trash-icon.svg
  types/type.ts
Labels: ⚙️ feat

#130 [fix]버그수정-06.25
  components/Modal/Schedule/ScheduleCreate/index.tsx
  components/Modal/Schedule/ScheduleDetail/ScheduleDetailModal.module.scss
  components/Modal/Schedule/ScheduleDetail/index.tsx
  hooks/useDragSelect.ts
  pages/calendar/components/Calendar/DailyCalendar/index.tsx
  pages/calendar/components/Calendar/MonthlyCalendar/index.tsx
  pages/calendar/components/Calendar/WeeklyCalendar/index.tsx
Labels: 🛠️ fix

#131 [feat]일정 생성하기 버튼 연결 구현
  pages/calendar/components/CalendarSideBar/index.tsx
Labels: ⚙️ feat

#136 [refactor]일정 삭제수정
  components/Modal/Schedule/ScheduleDetail/index.tsx
  hooks/useDeleteSchedule.ts
Labels: 🔨 refactor
